/**
 * Popular artist names used as fallback for artist suggestions.
 * These span multiple genres to provide diverse recommendations
 * when user preferences are unavailable or limited.
 */
export const POPULAR_ARTISTS = [
    'Taylor Swift',
    'Dua Lipa',
    'Ariana Grande',
    'Olivia Rodrigo',
    'Sabrina Carpenter',
    'Billie Eilish',
    'The Weeknd',
    'Drake',
    'Kendrick Lamar',
    'Travis Scott',
    'J. Cole',
    'Tyler The Creator',
    'Future',
    'Nicki Minaj',
    'Foo Fighters',
    'Red Hot Chili Peppers',
    'Arctic Monkeys',
    'Radiohead',
    'The Strokes',
    'Tame Impala',
    'SZA',
    'Frank Ocean',
    'Bruno Mars',
    'H.E.R.',
    'Daniel Caesar',
    'Daft Punk',
    'Calvin Harris',
    'Flume',
    'ODESZA',
    'Disclosure',
    'Skrillex',
    'Bad Bunny',
    'Anitta',
    'Karol G',
    'J Balvin',
    'Rosalía',
    'Peso Pluma',
    'Morgan Wallen',
    'Luke Combs',
    'Kacey Musgraves',
    'Zach Bryan',
    'Phoebe Bridgers',
    'Arcade Fire',
    'Vampire Weekend',
    'Mac DeMarco',
    'BTS',
    'BLACKPINK',
    'NewJeans',
    'Stray Kids',
    'The Beatles',
    'Queen',
    'Pink Floyd',
    'Led Zeppelin',
    'Miles Davis',
    'John Coltrane',
    'Nina Simone',
    'Metallica',
    'Tool',
    'System of a Down',
    'Matuê',
    'Tim Bernardes',
    'Racionais',
    'Djonga',
] as const

export type PopularArtist = (typeof POPULAR_ARTISTS)[number]
